// File generated by FlutterFire CLI.
// The FlutterFire CLI is an extension of the Firebase CLI

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macOS - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDedDYAzHO580vVCMn31aOISwZySW1QpHY',
    appId: '1:29206482394:android:ecd5c732fee662edc084e3',
    messagingSenderId: '29206482394',
    projectId: 'prakash-agro-services',
    storageBucket: 'prakash-agro-services.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDedDYAzHO580vVCMn31aOISwZySW1QpHY',
    appId: '1:29206482394:ios:ecd5c732fee662edc084e3',
    messagingSenderId: '29206482394',
    projectId: 'prakash-agro-services',
    storageBucket: 'prakash-agro-services.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDedDYAzHO580vVCMn31aOISwZySW1QpHY',
    appId: '1:29206482394:web:ecd5c732fee662edc084e3',
    messagingSenderId: '29206482394',
    projectId: 'prakash-agro-services',
    storageBucket: 'prakash-agro-services.firebasestorage.app',
  );
}